spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1200000
management:
  endpoints:
    web:
      exposure:
        include: "*"
